#!/bin/bash

function getandcheck {
    curl -L -s "$1" > $2
    filesize=`du -s $2 | awk '{print $1}'`
    if [[ "$filesize" -eq 8 ]]; then
        contents=`cat $2`
        if [ "$contents" = "AccessDenied" ]; then
            exit 1
        fi
    fi
}

if [ $# -eq 1 ]; then
    if [ "$1" == "-classad" ]; then
        echo 'PluginVersion = "0.1"'
        echo 'PluginType = "FileTransfer"'
        echo 'SupportedMethods = "http,https"'
    fi
elif [ $# -eq 2 ]; then
    cd `dirname $2`
    if [ ! -d "userhome" ]; then
        mkdir -p userhome
    fi
    cd userhome
    name=`basename "$1"`
    tmpname="${name%\?*}"
    if echo "$2" | grep -q .tgz; then
        getandcheck "$1" $tmpname
        tar xzf $tmpname
        rm -f $tmpname
    elif echo "$2" | grep -q .tar.gz; then
        getandcheck "$1" $tmpname
        tar xzf $tmpname
        rm -f $tmpname
    elif echo "$2" | grep -q .tar.bz2; then
        getandcheck "$1" $tmpname
        tar xjf $tmpname > /dev/null 2>&1
        rm -f $tmpname
    elif echo "$2" | grep -q .tar; then
        getandcheck "$1" $tmpname
        tar xf $tmpname > /dev/null 2>&1
        rm -f $tmpname
    elif echo "$2" | grep -q .gz; then
        getandcheck "$1" $tmpname
        gunzip $tmpname > /dev/null 2>&1
        rm -f $tmpname
    elif echo "$2" | grep -q .bz2; then
        getandcheck "$1" $tmpname
        bunzip2 $tmpname > /dev/null 2>&1
        rm -f $tmpname
    elif echo "$2" | grep -q .zip; then
        getandcheck "$1" $tmpname
        unzip $tmpname > /dev/null 2>&1
        rm -f $tmpname
    else
        getandcheck "$1" $tmpname
    fi
fi
