#!/usr/bin/python
import urllib
import json

url = "https://geolocation-db.com/json"
response = urllib.urlopen(url)
data = json.loads(response.read())
print 'ProminenceLocation="%f,%f"' % (data['latitude'],data['longitude'])
